- hosts: ruby
  roles:
    - role: worker
      node_version: 5.12.0
    - role: jobscore.ruby
      ruby_version: 2.3.5
      ruby_bundler_version: 1.15.4
      rack_gem_version: 1.6.8
      sinatra_gem_version: 1.4.7
