- hosts: ruby
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: Ensure needed packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - ca-certificates
        - curl
        - git
        - libc6-dev
        - libreadline-dev
        - libreadline6-dev
        - libsqlite3-dev
        - libssl-dev
        - libxml2-dev
        - libxslt-dev
        - libyaml-dev
        - make
        - sqlite3
        - zlib1g-dev
        - postgresql-client
        - imagemagick
        - libpq-dev
        - libmysqlclient-dev
  roles:
    - role: worker
      node_version: 5.12.0
    - role: jobscore.ruby
      ruby_version: 2.3.5
      ruby_bundler_version: 1.15.4
      rack_gem_version: 1.6.8
      sinatra_gem_version: 1.4.7
