---
# defaults file for jobscore_app
server_name: _

db_host: db
db_username: postgres
db_password: password

workdir: /code

nginx_environment: development

node_version: 5.12.0

ruby_version: 2.1.6

sphinx_version: 2.2.10
