--- # Configure pre-requisites
- name: Add postgres key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
    validate_certs: no

- name: Add postgres pkg repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql
  register: pgkey

- name: Update cache
  apt:
    update_cache: yes
  when: pgkey|changed

- name: Install needed packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libpq-dev
    - build-essential
    - libmysqlclient-dev
    - libssl-dev
    - git
    - wget
    - tzdata
    - libreadline-dev
    - postgresql-client-9.6
    - gcc
    - g++
    - clang-3.5
    - imagemagick
    - libstemmer-dev
    - ca-certificates
    - curl
    - libc6-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - make
    - sqlite3
