--- # Install passenger and configure app

- name: Install passenger and configure app
  include_role:
    name: geerlingguy.passenger
  vars:
    passenger_server_name: "{{ server_name }}"
    passenger_app_root: "{{workdir}}/public"
    passenger_app_env: "{{ nginx_environment }}"
    passenger_ruby: /usr/local/bin/ruby
